### PR TITLE
Demo title Add files via upload

### PR DESCRIPTION
**Pull request by bobpoop500000**

### CODE REVIEW

**Comment by effigies** [comment]
@coldfumonkeh Note that the actions are still running:

* https://github.com/coldfumonkeh/oauth2/runs/2363729053
* https://github.com/coldfumonkeh/oauth2/runs/2363758755
* ...

**Comment by mjclemente** [comment]
How does this work? Someone can just open a PR with GitHub Actions and run them on your repo?

**Comment by effigies** [comment]
Yup... Once you have GHA enabled, they have to be changeable in a PR (otherwise how do you test fixes/improvements to CI?). It works with other CIs, too.

It's a gaping hole, and making it so that a maintainer has to actively enable them for new contributors seems like an obvious fix on the GitHub end, but it's been going on for several months at least and AFAICT they're manually inspecting abuse reports while letting their servers enrich these sociopaths for days per burner account.

**Comment by mjclemente** [comment]
🤯🤯🤯

Thanks for sharing - that's just crazy.

**Pull request closed without merging**
