### PR TITLE
Update oauth2.cfc

### PR DESCRIPTION
**Pull request by KrunchMuffin**
update to using `cfhttp()` instead of `new http()`

### CODE REVIEW

**Comment by kevindb** [comment]
`new http()` works as far back at ACF9. The `cfhttp()` syntax was only added in ACF11, right? What benefit does moving to `cfhttp()` provide that is worth reducing backward compatibility?

**Comment by KrunchMuffin** [comment]
Just going by this
https://www.raymondcamden.com/2015/02/11/reminder-stop-using-the-old-cfc-based-tags-in-coldfusion-11

Maybe just add a cf11 branch?

**Comment by coldfumonkeh** [comment]
I'd be hesitant to create a version-specific branch TBH, as it opens up too many issues for maintenance and management. The core branch was built to be as fully-backwards compatible as possible and I'd like to keep it that way to make life easier.

**Comment by KrunchMuffin** [comment]
No worries

**Comment by coldfumonkeh** [comment]
I'm VERY happy to see public action on this repo though, thank you!

**Comment by LittleDeveloper26** [comment]
@coldfumonkeh can I use oauth2.cfc you provided in a code written in CF10?

**Pull request closed without merging**
